### ISSUE TITLE
error about lootables 1.9.4

### ISSUE THREAD

**Issue by wackoamd1** [Shinoow/AbyssalCraft#100]
[Server thread/ERROR]: Couldn't load loot table abyssalcraft:chests/mineshaft from jar:file:/home/minecraft/servers/mine69074/mods/AbyssalCraft-1.9.4-1.9.1.6.jar!/assets/abyssalcraft/loot_tables/chests/mineshaft.json
com.google.gson.JsonParseException: Loot Table "abyssalcraft:chests/mineshaft" Missing `name` entry for pool #0
	at net.minecraftforge.common.ForgeHooks.readPoolName(ForgeHooks.java:1088) ~[ForgeHooks.class:?]
	at net.minecraft.world.storage.loot.LootPool$Serializer.deserialize(LootPool.java:143) ~[azu$a.class:?]
	at net.minecraft.world.storage.loot.LootPool$Serializer.deserialize(LootPool.java:138) ~[azu$a.class:?]
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[TreeTypeAdapter.class:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[TypeAdapterRuntimeTypeWrapper.class:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[ArrayTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:868) ~[Gson.class:?]
	at com.google.gson.Gson$1.deserialize(Gson.java:126) ~[Gson$1.class:?]
	at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:449) ~[oe.class:?]
	at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:465) ~[oe.class:?]
	at net.minecraft.world.storage.loot.LootTable$Serializer.deserialize(LootTable.java:206) ~[azw$a.class:?]
	at net.minecraft.world.storage.loot.LootTable$Serializer.deserialize(LootTable.java:201) ~[azw$a.class:?]
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:768) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:717) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:689) ~[Gson.class:?]
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:1012) ~[ForgeHooks.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.func_186518_c(LootTableManager.java:148) [azz$a.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:71) [azz$a.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:52) [azz$a.class:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) [minecraft_server.1.9.4.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) [minecraft_server.1.9.4.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) [minecraft_server.1.9.4.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) [minecraft_server.1.9.4.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934) [minecraft_server.1.9.4.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) [minecraft_server.1.9.4.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) [minecraft_server.1.9.4.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) [minecraft_server.1.9.4.jar:?]
	at net.minecraft.world.storage.loot.LootTableManager.func_186521_a(LootTableManager.java:39) [azz.class:?]
	at net.minecraft.world.storage.loot.LootTableManager.func_186522_a(LootTableManager.java:48) [azz.class:?]
	at net.minecraft.world.storage.loot.LootTableManager.<init>(LootTableManager.java:34) [azz.class:?]
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:152) [lq.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:251) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:263) [lb.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:429) 

thats with mc.1.9.4 and forge 1.9.4-12.17.0.1910

**Comment by Shinoow** [comment]
Yeah, made a typo for the new forge loot table syntax in the 1.9.4 port. Will be fixed in the next release.
