### ISSUE TITLE
Misc information in the JEI plugin

### ISSUE THREAD

**Issue by Shinoow** [Shinoow/AbyssalCraft#142]
After a bit of thinking, there is more information that could be displayed through JEI (what came to mind was obtaining the essences, so displaying that you get "essence x" through the usage of a Staff of Rending). I've opened this issue so people can suggest more things to be displayed through JEI. Have an idea? Comment!

**Comment by mrtopf** [comment]
just a small thing: The usage function does not work for the charms to show up the rituals you can use them in (e.g. hastur charm, amplifier: none does not show anything when pressing u). I guess that's true for all the items being used in rituals.

**Comment by Shinoow** [comment]
Yeah, I think the format of the rituals prevent usage searching from working correctly. I'm gonna look into that and see if there's a way for it to work for those as well.

**Comment by Shinoow** [comment]
Something I forgot to include in 1.9.4-pre-1 was a way to display the Upgrade Kit usage recipes (since they no longer do their thing in a crafting grid, but now in an anvil instead). That's something I plan on including in the next update after that one.

**Comment by Alaberti** [comment]
Not sure if it's relevant or needs a new issue, but from my MC 1.12.2, ver 1.9.4-pre-4 client console:

[B#353]  [15:08:48] [main/ERROR] [jei]: Failed to register mod plugin: class com.shinoow.abyssalcraft.integration.jei.ACJEIPlugin
[B#353]  java.lang.IllegalArgumentException: Must have at least 1 tick per cycle.
[B#353]  	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[guava-21.0.jar:?]
[B#353]  	at mezz.jei.gui.TickTimer.<init>(TickTimer.java:13) ~[TickTimer.class:?]
[B#353]  	at mezz.jei.gui.GuiHelper.createTickTimer(GuiHelper.java:106) ~[GuiHelper.class:?]
[B#353]  	at mezz.jei.gui.GuiHelper.createAnimatedDrawable(GuiHelper.java:85) ~[GuiHelper.class:?]
[B#353]  	at com.shinoow.abyssalcraft.integration.jei.transmutator.TransmutatorFuelRecipe.<init>(TransmutatorFuelRecipe.java:44) ~[TransmutatorFuelRecipe.class:?]
[B#353]  	at com.shinoow.abyssalcraft.integration.jei.transmutator.TransmutatorFuelRecipeMaker.getFuelRecipes(TransmutatorFuelRecipeMaker.java:55) ~[TransmutatorFuelRecipeMaker.class:?]
[B#353]  	at com.shinoow.abyssalcraft.integration.jei.ACJEIPlugin.register(ACJEIPlugin.java:85) ~[ACJEIPlugin.class:?]
[B#353]  	at mezz.jei.startup.JeiStarter.registerPlugins(JeiStarter.java:170) [JeiStarter.class:?]
[B#353]  	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:57) [JeiStarter.class:?]
[B#353]  	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:116) [ProxyCommonClient.class:?]
[B#353]  	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:54) [JustEnoughItems.class:?]
[B#353]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
[B#353]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
[B#353]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
[B#353]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_141]
[B#353]  	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:611) [FMLModContainer.class:?]
[B#353]  	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
[B#353]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
[B#353]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_141]
[B#353]  	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
[B#353]  	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
[B#353]  	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
[B#353]  	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
[B#353]  	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
[B#353]  	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
[B#353]  	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
[B#353]  	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253) [LoadController.class:?]
[B#353]  	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231) [LoadController.class:?]
[B#353]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
[B#353]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
[B#353]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
[B#353]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_141]
[B#353]  	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
[B#353]  	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
[B#353]  	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
[B#353]  	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
[B#353]  	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
[B#353]  	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
[B#353]  	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
[B#353]  	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148) [LoadController.class:?]
[B#353]  	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:789) [Loader.class:?]
[B#353]  	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:348) [FMLClientHandler.class:?]
[B#353]  	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534) [bib.class:?]
[B#353]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bib.class:?]
[B#353]  	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
[B#353]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
[B#353]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
[B#353]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
[B#353]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_141]
[B#353]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[B#353]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by Shinoow** [comment]
I'm gonna take a wild guess and say something internal has changed in JEI since 1.12. Considering the next release will probably be for 1.12.2, I'll investigate this further.

**Comment by C0rn3j** [comment]
Still an issue on 1.12.2, forge 2758 and AC 1.9.4.11
```
[20:24:50] [main/ERROR] [jei]: Failed to register mod plugin: class com.shinoow.abyssalcraft.integration.jei.ACJEIPlugin
java.lang.UnsupportedOperationException: null
	at java.util.Collections$SingletonList.removeIf(Collections.java:4826) ~[?:1.8.0_181]
	at com.shinoow.abyssalcraft.integration.jei.transmutator.TransmutatorFuelRecipeMaker.removeNoBurnTime(TransmutatorFuelRecipeMaker.java:78) ~[TransmutatorFuelRecipeMaker.class:?]
	at com.shinoow.abyssalcraft.integration.jei.transmutator.TransmutatorFuelRecipeMaker.getFuelRecipes(TransmutatorFuelRecipeMaker.java:61) ~[TransmutatorFuelRecipeMaker.class:?]
	at com.shinoow.abyssalcraft.integration.jei.ACJEIPlugin.register(ACJEIPlugin.java:89) ~[ACJEIPlugin.class:?]
	at mezz.jei.startup.JeiStarter.registerPlugins(JeiStarter.java:181) [JeiStarter.class:?]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:64) [JeiStarter.class:?]
	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:120) [ProxyCommonClient.class:?]
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:54) [JustEnoughItems.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627) [FMLModContainer.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```
