### ISSUE TITLE
Crash when using the staff of rending on a zombie

### ISSUE THREAD

**Issue by mrtopf** [Shinoow/AbyssalCraft#148]
I tried to figure out how to use the staff of rending (the book only says that I have to use it) and right clicked on a zombie in the first dimension. Then the game crashed with the following stack trace:

```
[21:42:43] [Client thread/WARN]: Received passengers for unknown entity
[21:42:43] [Client thread/WARN]: Received passengers for unknown entity
[21:42:45] [Client thread/WARN]: Received passengers for unknown entity
[21:43:27] [Netty Server IO #1/ERROR] [FML]: There was a critical exception handling a packet on channel abyssalcraft
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[MessageToMessageEncoder.class:4.0.23.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) ~[DefaultChannelPipeline.class:4.0.23.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) ~[AbstractChannel.class:4.0.23.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToDimension(SimpleNetworkWrapper.java:277) ~[SimpleNetworkWrapper.class:?]
	at com.shinoow.abyssalcraft.common.network.PacketDispatcher.sendToDimension(PacketDispatcher.java:132) ~[PacketDispatcher.class:?]
	at com.shinoow.abyssalcraft.common.handlers.InternalMethodHandler.sendDisruption(InternalMethodHandler.java:25) ~[InternalMethodHandler.class:?]
	at com.shinoow.abyssalcraft.api.energy.disruption.DisruptionHandler.generateDisruption(DisruptionHandler.java:111) ~[DisruptionHandler.class:?]
	at com.shinoow.abyssalcraft.common.blocks.tile.TileEntityRitualAltar.func_73660_a(TileEntityRitualAltar.java:136) ~[TileEntityRitualAltar.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1804) ~[aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619) ~[ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) ~[bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at com.shinoow.abyssalcraft.common.network.client.DisruptionMessage.write(DisruptionMessage.java:60) ~[DisruptionMessage.class:?]
	at com.shinoow.abyssalcraft.common.network.AbstractMessage.toBytes(AbstractMessage.java:100) ~[AbstractMessage.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30) ~[SimpleIndexedCodec.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:73) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:4.0.23.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[MessageToMessageEncoder.class:4.0.23.Final]
	... 19 more
```

**Comment by Shinoow** [comment]
Judging by the crash report, it seems like someone failed a ritual, and then the disruption mechanic messed up because I apparently had it input a null deity type (and nulls aren't good in that particular situation).
