### ISSUE TITLE
Halloween Easter Egg Bug

### ISSUE THREAD

**Issue by TLomon** [Shinoow/AbyssalCraft#158]
Just crashed our server. Here is the relevant portion of the error:

java.lang.ArrayIndexOutOfBoundsException: 4
	at com.shinoow.abyssalcraft.common.entity.EntityAbyssalZombie.func_180482_a(EntityAbyssalZombie.java:402)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:154)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:198)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

This exists in 3.1, 3.2, and 3.3 at the very least. We are trying some work arounds.

**Comment by TLomon** [comment]
Appears to be a duplicate of #155. Sorry I didn't notice it at first.
