### ISSUE TITLE
Server Crash ArrayIndexOutOfBoundsException EntityAbyssalZombie.fun

### ISSUE THREAD

**Issue by ProsperCraft** [Shinoow/AbyssalCraft#160]
https://gist.github.com/ProsperCraft/ac11d5f0ccd7ab4e0e885b4972f07f41

Description: Exception ticking world

java.lang.ArrayIndexOutOfBoundsException: 4
	at com.shinoow.abyssalcraft.common.entity.EntityAbyssalZombie.func_180482_a(EntityAbyssalZombie.java:402)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:154)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:198)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ProsperCraft** [comment]
Here is another one.
https://gist.github.com/ProsperCraft/aa256031a3dc65928e67fa5d61435d7e

**Comment by Shinoow** [comment]
Update to 1.9.3.4, this was fixed there.
