### ISSUE TITLE
Too many errors in console from AbyssalCraft

### ISSUE THREAD

**Issue by Kubikx** [Shinoow/AbyssalCraft#235]
`[09:47:57] [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[MessageToMessageEncoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToDimension(SimpleNetworkWrapper.java:277) [SimpleNetworkWrapper.class:?]
        at com.shinoow.abyssalcraft.common.network.PacketDispatcher.sendToDimension(PacketDispatcher.java:142) [PacketDispatcher.class:?]
        at com.shinoow.abyssalcraft.common.handlers.InternalMethodHandler.sendDisruption(InternalMethodHandler.java:33) [InternalMethodHandler.class:?]
        at com.shinoow.abyssalcraft.api.energy.disruption.DisruptionHandler.generateDisruption(DisruptionHandler.java:112) [DisruptionHandler.class:?]
        at com.shinoow.abyssalcraft.common.blocks.tile.TileEntityStatue.disrupt(TileEntityStatue.java:173) [TileEntityStatue.class:?]
        at com.shinoow.abyssalcraft.common.blocks.tile.TileEntityStatue.func_73660_a(TileEntityStatue.java:210) [TileEntityStatue.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1807) [ams.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614) [om.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:391) [nx.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at com.shinoow.abyssalcraft.common.network.client.DisruptionMessage.write(DisruptionMessage.java:60) ~[DisruptionMessage.class:?]
        at com.shinoow.abyssalcraft.common.network.AbstractMessage.toBytes(AbstractMessage.java:99) ~[AbstractMessage.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30) ~[SimpleIndexedCodec.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
        at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:73) ~[FMLIndexedMessageToMessageCodec.class:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[MessageToMessageEncoder.class:?]
        ... 21 more
[09:47:57] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[MessageToMessageEncoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToDimension(SimpleNetworkWrapper.java:277) [SimpleNetworkWrapper.class:?]
        at com.shinoow.abyssalcraft.common.network.PacketDispatcher.sendToDimension(PacketDispatcher.java:142) [PacketDispatcher.class:?]
        at com.shinoow.abyssalcraft.common.handlers.InternalMethodHandler.sendDisruption(InternalMethodHandler.java:33) [InternalMethodHandler.class:?]
        at com.shinoow.abyssalcraft.api.energy.disruption.DisruptionHandler.generateDisruption(DisruptionHandler.java:112) [DisruptionHandler.class:?]
        at com.shinoow.abyssalcraft.common.blocks.tile.TileEntityStatue.disrupt(TileEntityStatue.java:173) [TileEntityStatue.class:?]
        at com.shinoow.abyssalcraft.common.blocks.tile.TileEntityStatue.func_73660_a(TileEntityStatue.java:210) [TileEntityStatue.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1807) [ams.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614) [om.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:391) [nx.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at com.shinoow.abyssalcraft.common.network.client.DisruptionMessage.write(DisruptionMessage.java:60) ~[DisruptionMessage.class:?]
        at com.shinoow.abyssalcraft.common.network.AbstractMessage.toBytes(AbstractMessage.java:99) ~[AbstractMessage.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30) ~[SimpleIndexedCodec.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
        at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:73) ~[FMLIndexedMessageToMessageCodec.class:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[MessageToMessageEncoder.class:?]
        ... 21 more
[09:47:57] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[MessageToMessageEncoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToDimension(SimpleNetworkWrapper.java:277) [SimpleNetworkWrapper.class:?]
        at com.shinoow.abyssalcraft.common.network.PacketDispatcher.sendToDimension(PacketDispatcher.java:142) [PacketDispatcher.class:?]
        at com.shinoow.abyssalcraft.common.handlers.InternalMethodHandler.sendDisruption(InternalMethodHandler.java:33) [InternalMethodHandler.class:?]
        at com.shinoow.abyssalcraft.api.energy.disruption.DisruptionHandler.generateDisruption(DisruptionHandler.java:112) [DisruptionHandler.class:?]
        at com.shinoow.abyssalcraft.common.blocks.tile.TileEntityStatue.disrupt(TileEntityStatue.java:173) [TileEntityStatue.class:?]
        at com.shinoow.abyssalcraft.common.blocks.tile.TileEntityStatue.func_73660_a(TileEntityStatue.java:210) [TileEntityStatue.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1807) [ams.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614) [om.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:391) [nx.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at com.shinoow.abyssalcraft.common.network.client.DisruptionMessage.write(DisruptionMessage.java:60) ~[DisruptionMessage.class:?]
        at com.shinoow.abyssalcraft.common.network.AbstractMessage.toBytes(AbstractMessage.java:99) ~[AbstractMessage.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30) ~[SimpleIndexedCodec.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
        at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:73) ~[FMLIndexedMessageToMessageCodec.class:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[MessageToMessageEncoder.class:?]
        ... 21 more
[09:47:57] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[MessageToMessageEncoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToDimension(SimpleNetworkWrapper.java:277) [SimpleNetworkWrapper.class:?]
        at com.shinoow.abyssalcraft.common.network.PacketDispatcher.sendToDimension(PacketDispatcher.java:142) [PacketDispatcher.class:?]
        at com.shinoow.abyssalcraft.common.handlers.InternalMethodHandler.sendDisruption(InternalMethodHandler.java:33) [InternalMethodHandler.class:?]
        at com.shinoow.abyssalcraft.api.energy.disruption.DisruptionHandler.generateDisruption(DisruptionHandler.java:112) [DisruptionHandler.class:?]
        at com.shinoow.abyssalcraft.common.blocks.tile.TileEntityStatue.disrupt(TileEntityStatue.java:173) [TileEntityStatue.class:?]
        at com.shinoow.abyssalcraft.common.blocks.tile.TileEntityStatue.func_73660_a(TileEntityStatue.java:210) [TileEntityStatue.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1807) [ams.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614) [om.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:391) [nx.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at com.shinoow.abyssalcraft.common.network.client.DisruptionMessage.write(DisruptionMessage.java:60) ~[DisruptionMessage.class:?]
        at com.shinoow.abyssalcraft.common.network.AbstractMessage.toBytes(AbstractMessage.java:99) ~[AbstractMessage.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30) ~[SimpleIndexedCodec.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
        at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:73) ~[FMLIndexedMessageToMessageCodec.class:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[MessageToMessageEncoder.class:?]
        ... 21 more
[09:47:57] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[MessageToMessageEncoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToDimension(SimpleNetworkWrapper.java:277) [SimpleNetworkWrapper.class:?]
        at com.shinoow.abyssalcraft.common.network.PacketDispatcher.sendToDimension(PacketDispatcher.java:142) [PacketDispatcher.class:?]
        at com.shinoow.abyssalcraft.common.handlers.InternalMethodHandler.sendDisruption(InternalMethodHandler.java:33) [InternalMethodHandler.class:?]
        at com.shinoow.abyssalcraft.api.energy.disruption.DisruptionHandler.generateDisruption(DisruptionHandler.java:112) [DisruptionHandler.class:?]
        at com.shinoow.abyssalcraft.common.blocks.tile.TileEntityStatue.disrupt(TileEntityStatue.java:173) [TileEntityStatue.class:?]
        at com.shinoow.abyssalcraft.common.blocks.tile.TileEntityStatue.func_73660_a(TileEntityStatue.java:210) [TileEntityStatue.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1807) [ams.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614) [om.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:391) [nx.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at com.shinoow.abyssalcraft.common.network.client.DisruptionMessage.write(DisruptionMessage.java:60) ~[DisruptionMessage.class:?]
        at com.shinoow.abyssalcraft.common.network.AbstractMessage.toBytes(AbstractMessage.java:99) ~[AbstractMessage.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30) ~[SimpleIndexedCodec.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
        at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:73) ~[FMLIndexedMessageToMessageCodec.class:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[MessageToMessageEncoder.class:?]
        ... 21 more
[09:47:57] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[MessageToMessageEncoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToDimension(SimpleNetworkWrapper.java:277) [SimpleNetworkWrapper.class:?]
        at com.shinoow.abyssalcraft.common.network.PacketDispatcher.sendToDimension(PacketDispatcher.java:142) [PacketDispatcher.class:?]
        at com.shinoow.abyssalcraft.common.handlers.InternalMethodHandler.sendDisruption(InternalMethodHandler.java:33) [InternalMethodHandler.class:?]
        at com.shinoow.abyssalcraft.api.energy.disruption.DisruptionHandler.generateDisruption(DisruptionHandler.java:112) [DisruptionHandler.class:?]
        at com.shinoow.abyssalcraft.common.blocks.tile.TileEntityStatue.disrupt(TileEntityStatue.java:173) [TileEntityStatue.class:?]
        at com.shinoow.abyssalcraft.common.blocks.tile.TileEntityStatue.func_73660_a(TileEntityStatue.java:210) [TileEntityStatue.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1807) [ams.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614) [om.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:391) [nx.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at com.shinoow.abyssalcraft.common.network.client.DisruptionMessage.write(DisruptionMessage.java:60) ~[DisruptionMessage.class:?]
        at com.shinoow.abyssalcraft.common.network.AbstractMessage.toBytes(AbstractMessage.java:99) ~[AbstractMessage.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30) ~[SimpleIndexedCodec.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
        at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:73) ~[FMLIndexedMessageToMessageCodec.class:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[MessageToMessageEncoder.class:?]
        ... 21 more
[09:47:57] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[MessageToMessageEncoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToDimension(SimpleNetworkWrapper.java:277) [SimpleNetworkWrapper.class:?]
        at com.shinoow.abyssalcraft.common.network.PacketDispatcher.sendToDimension(PacketDispatcher.java:142) [PacketDispatcher.class:?]
        at com.shinoow.abyssalcraft.common.handlers.InternalMethodHandler.sendDisruption(InternalMethodHandler.java:33) [InternalMethodHandler.class:?]
        at com.shinoow.abyssalcraft.api.energy.disruption.DisruptionHandler.generateDisruption(DisruptionHandler.java:112) [DisruptionHandler.class:?]
        at com.shinoow.abyssalcraft.common.blocks.tile.TileEntityStatue.disrupt(TileEntityStatue.java:173) [TileEntityStatue.class:?]
        at com.shinoow.abyssalcraft.common.blocks.tile.TileEntityStatue.func_73660_a(TileEntityStatue.java:210) [TileEntityStatue.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1807) [ams.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614) [om.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:391) [nx.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at com.shinoow.abyssalcraft.common.network.client.DisruptionMessage.write(DisruptionMessage.java:60) ~[DisruptionMessage.class:?]
        at com.shinoow.abyssalcraft.common.network.AbstractMessage.toBytes(AbstractMessage.java:99) ~[AbstractMessage.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30) ~[SimpleIndexedCodec.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
        at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:73) ~[FMLIndexedMessageToMessageCodec.class:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[MessageToMessageEncoder.class:?]
        ... 21 more`

**Comment by Shinoow** [comment]
Huh, I seem to completely have missed getting those log errors. Anyhow, I know the cause of it.
