### ISSUE TITLE
[1.12.2] Bunch of exception's being fired caused by statue/network code.

### ISSUE THREAD

**Issue by MrNinja93** [Shinoow/AbyssalCraft#271]
Bunch of exceptions being logged in player console, seems to be caused by network back and forth involving the statue.

```SimpleChannelHandlerWrapper exception
java.lang.NullPointerException: null
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$7.selectNetworks(FMLOutboundHandler.java:216) ~[FMLOutboundHandler$OutboundTarget$7.class:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:297) ~[FMLOutboundHandler.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:263) [SimpleNetworkWrapper.class:?]
	at com.shinoow.abyssalcraft.common.network.PacketDispatcher.sendToAllAround(PacketDispatcher.java:121) [PacketDispatcher.class:?]
	at com.shinoow.abyssalcraft.common.network.PacketDispatcher.sendToAllAround(PacketDispatcher.java:128) [PacketDispatcher.class:?]
	at com.shinoow.abyssalcraft.common.handlers.InternalMethodHandler.spawnPEStream(InternalMethodHandler.java:43) [InternalMethodHandler.class:?]
	at com.shinoow.abyssalcraft.api.energy.PEUtils.transferPEToCollectors(PEUtils.java:136) [PEUtils.class:?]
	at com.shinoow.abyssalcraft.common.blocks.tile.TileEntityStatue.func_73660_a(TileEntityStatue.java:215) [TileEntityStatue.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1832) [amu.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]


````

Relevant latest log file, https://gist.github.com/MrNinja93/dc702460e2fc4d074242124b37f6f2f2

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft:1.12.2
- Forge: 14.23.2.2635
- AbyssalCraft: 1.9.4.5

**Comment by Shinoow** [comment]
The latest log doesn't really give any information at all (just the startup sequence). I don't see anything in particular that could be the cause based on the stack trace. Can you verify if the exception is being thrown on the client or the server? Can this be reproduced in another world with the same setup of statues and whatnot?
