### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by O13SC3N3** [Shinoow/AbyssalCraft#28]
Time: 3/30/15 1:40 PM
Description: Ticking entity

java.lang.NoClassDefFoundError: mods/betterfoliage/client/render/IRenderBlockDecorator
	at net.minecraft.block.Block.func_149710_n(Block.java:187)
	at net.minecraft.world.World.func_72849_a(World.java:771)
	at net.minecraft.world.World.func_72957_l(World.java:764)
	at net.minecraft.world.World.func_72801_o(World.java:1014)
	at net.minecraft.entity.Entity.func_70013_c(Entity.java:1106)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:21)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: mods.betterfoliage.client.render.IRenderBlockDecorator
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 19 more
Caused by: java.lang.RuntimeException: Attempted to load class mods/betterfoliage/client/render/IRenderBlockDecorator for invalid side SERVER
	at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 21 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.Block.func_149710_n(Block.java:187)
	at net.minecraft.world.World.func_72849_a(World.java:771)
	at net.minecraft.world.World.func_72957_l(World.java:764)
	at net.minecraft.world.World.func_72801_o(World.java:1014)
	at net.minecraft.entity.Entity.func_70013_c(Entity.java:1106)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:21)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: abyssalcraft.evilpig (com.shinoow.abyssalcraft.common.entity.EntityEvilpig)
	Entity ID: 243
	Entity Name: Pig
	Entity's Exact location: -351.50, 63.00, 25.50
	Entity's Block location: World: (-352,63,25), Chunk: (at 0,3,9 in -22,1; contains blocks -352,0,16 to -337,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 808 Drop: 0
	Level seed: 349045171753229897
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-230,64,43), Chunk: (at 10,4,11 in -15,2; contains blocks -240,0,32 to -225,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1 game time, 1 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 25830 (now: false), thunder time: 160087 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by O13SC3N3** [comment]
With better Foliage Disabled. Same Seed, Same World, and even on New World Generation.

java.lang.NoClassDefFoundError: net/minecraft/client/particle/EntityFX
	at net.minecraft.block.Block.func_149710_n(Block.java:187)
	at net.minecraft.world.World.func_72849_a(World.java:771)
	at net.minecraft.world.World.func_72957_l(World.java:764)
	at net.minecraft.world.World.func_72801_o(World.java:1014)
	at net.minecraft.entity.Entity.func_70013_c(Entity.java:1106)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:21)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.EntityFX
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 19 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.Block.func_149710_n(Block.java:187)
	at net.minecraft.world.World.func_72849_a(World.java:771)
	at net.minecraft.world.World.func_72957_l(World.java:764)
	at net.minecraft.world.World.func_72801_o(World.java:1014)
	at net.minecraft.entity.Entity.func_70013_c(Entity.java:1106)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:21)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: abyssalcraft.evilpig (com.shinoow.abyssalcraft.common.entity.EntityEvilpig)
	Entity ID: 57
	Entity Name: Pig
	Entity's Exact location: -339.50, 63.00, -93.50
	Entity's Block location: World: (-340,63,-94), Chunk: (at 12,3,2 in -22,-6; contains blocks -352,0,-96 to -337,255,-81), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 349045171753229897
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-230,64,43), Chunk: (at 10,4,11 in -15,2; contains blocks -240,0,32 to -225,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2 game time, 2 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 25829 (now: false), thunder time: 160086 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Shinoow** [comment]
Something client-side is getting called server side, can't say my mod has that much to do with it, as the Evil Pig never calls anything client-side, which would mean another mod is doing something client-side on the server.

**Comment by O13SC3N3** [comment]
Doesn't appear when Abyssal Craft is Removed.

**Comment by Shinoow** [comment]
The crash report doesn't mention a single line of code from my mod, so I can't really see where it triggers from.

**Comment by O13SC3N3** [comment]
haven't used AbysalCraft since the issue, closing report.
