### ISSUE TITLE
1.9.7 CCL spam in chat, but no ccl config to make the change in

### ISSUE THREAD

**Issue by kreezxil** [Shinoow/AbyssalCraft#364]
client latest log: 
http://paste.ubuntu.com/p/kvsqMJVrFM/ starting at line 6632

the repeating error
```
[17:46:17] [Chunk Batcher 6/ERROR]: 
 CCL has caught an exception whilst rendering a block
  BlockPos:      x:-78, y:86, z:177
  Block Class:   class com.shinoow.abyssalcraft.common.blocks.BlockOmotholFire
  Registry Name: abyssalcraft:omotholfire
  Metadata:      0
  State:         abyssalcraft:omotholfire
 Tile at position
  Tile Class:    null
  Tile Id:       null
  Tile NBT:      null
You can turn off player messages in the CCL config file.

net.minecraft.util.ReportedException: Tesselating block in world
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:95) ~[bvm.class:?]
	at codechicken.lib.render.block.CCBlockRendererDispatcher.renderBlock(CCBlockRendererDispatcher.java:82) [CCBlockRendererDispatcher.class:?]
	at net.minecraft.client.renderer.chunk.RenderChunk.rebuildChunk(RenderChunk.java:200) [bxr.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.processTask(SourceFile:100) [bxn.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43) [bxn.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at net.minecraft.block.Block.shouldSideBeRendered(Block.java:402) ~[aow.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.shouldSideBeRendered(BlockStateContainer.java:435) ~[awu$a.class:?]
	at team.chisel.ctm.client.state.CTMExtendedState.shouldSideBeRendered(CTMExtendedState.java:36) ~[CTMExtendedState.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.handler$beforeRenderModel$zcb000(BlockModelRenderer.java:544) ~[bvo.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java) ~[bvo.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:38) ~[bvo.class:?]
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:80) ~[bvm.class:?]
	... 5 more
```

Is this to do with abyssalcraft at all or something else?

**Comment by kreezxil** [comment]
I realize now that CCL is codechicken library, but why is it tripping on your mod? should I report this to codechicken too?

**Comment by Andromander** [comment]
I've seen this issue elsewhere, and it was resolved on the affected block's side. You can keep it open here.

**Comment by kreezxil** [comment]
so there's a mod update coming that has the fix?

**Comment by Andromander** [comment]
As in I've seen this issue on another mod, not that there is a fix for this mod currently.

**Comment by kreezxil** [comment]
I've found where to make the setting, turns out CCL is refering to
codechickenlibrary.cfg which apparently a long long time ago in this galaxy
used to be called ccl.cfg and well also ccl. Anyhoo, there's a setting in
there that wasn't there before, that turns off these announcements.

go ahead and close this.

thanks.
