### ISSUE TITLE
Client crash on forge 1448

### ISSUE THREAD

**Issue by pabluuz** [Shinoow/AbyssalCraft#38]
Hey, it looks like fluid registry problem is back again

Reproduce: Use your mod with newest thaumcraft on forge 1448 or newer.

[17:41:03] [Client thread/ERROR] [FML/]: FluidIdRegistryMessageHandler exception
java.lang.IllegalArgumentException: value already present: gaseousdreadiaessentia
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:238) ~[guava-17.0.jar:?]
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:215) ~[guava-17.0.jar:?]
	at net.minecraftforge.fluids.FluidRegistry.loadFluidDefaults(FluidRegistry.java:117) ~
...

Do You need full crashlog, or forgelog?

**Comment by Shinoow** [comment]
That should be reported to Azanor, as I haven't added any fluid for any of the Aspects added through my Thaumcraft integration.
The fluid registry problem people had earlier was due to the rapid removal of a method in the registry that I used, resulting in crashes related to the specific method missing (since it had been removed).

**Comment by pabluuz** [comment]
Sure, I'll forward this to Azanor. I've made issue submission here first because when I disabled AbyssalCraft, the problem was gone.
