### ISSUE TITLE
Abyssal Wasteland not working properly

### ISSUE THREAD

**Issue by dikkefed** [Shinoow/AbyssalCraft#448]
![mods](https://user-images.githubusercontent.com/71384843/93334921-f66c6a00-f825-11ea-959a-95c866fe6f57.png)

#### Intro:
I went with the progression system as intended, got mah shadowgems, made a gateway key, spawned a portal. unfortunately upon teleporting in the abyssal wasteland, i keep dying within first 5 seconds due to overheating. I tried to cheese it out with different armor sets, including quantum suit from IC2, to no avail. Death message states "Died due overheating". 

#### Description:
I have this in a selfmade modpack (not public use, i respect fair trade), i thought this was a modpack conflict, specifically advanced rocketry, however i couldnt find any evidence for that except the log provided. list of the mods i have picrelated
#### Affected versions ("latest" is **NOT** a version):
- Minecraft:1.12.2
- Forge:14.23.5.2854
- AbyssalCraft:1.10.2.jar

#### Latest log file for when the issue was present:
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: java.lang.IllegalStateException: Cannot load server config when already using server config!
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: 	at zmaster587.advancedRocketry.api.ARConfiguration.loadConfigFromServer(ARConfiguration.java:382)
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: 	at zmaster587.advancedRocketry.network.PacketConfigSync.executeClient(PacketConfigSync.java:52)
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: 	at zmaster587.libVulpes.network.BasePacket$BasePacketHandlerClient$executor.run(BasePacket.java:155)
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: 	at net.minecraft.util.Util.func_181617_a(Util.java:47)
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088)
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[13:40:17] [Client thread/INFO] [STDERR]: [zmaster587.advancedRocketry.network.PacketConfigSync:executeClient:54]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[13:40:20] [Netty Client IO #2/INFO] [tconstruct-Config]: Syncing Config with Server
[13:40:20] [Client thread/INFO] [projecte]: Receiving EMC data from server.
[13:40:20] [Client thread/INFO] [minecraft/AdvancementList]: Loaded 1179 advancements
[13:40:25] [Client thread/INFO] [minecraft/GuiNewChat]: [CHAT] fedorzyblev died due to overheating
[13:40:45] [Client thread/INFO] [foamfix]: Unloaded world
[pastebin/gist/etc link here]

**Comment by Shinoow** [comment]
That is most likely caused by Advanced Rocketry. The mod has a tendency of thinking dimensions from other mods are planets, which makes it apply its various planet-related mechanics on those dimensions regardless of whether or not they're actually planets. If you look through the config file of that mod you'll likely stumble upon something where you can stop that from happening.
