### ISSUE TITLE
Dedicated server crash - Inconsistent stackmap frames

### ISSUE THREAD

**Issue by kwpugh** [Shinoow/AbyssalCraft#54]
Full crash report:  http://pastebin.com/YzkMFkG6

Server keeps crashing unless  I move players out of the noted check location.

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 12/30/15 8:29 PM
Description: Exception ticking world

java.lang.VerifyError: Inconsistent stackmap frames at branch target 32
Exception Details:
  Location:
    com/shinoow/abyssalcraft/common/entity/EntityLesserShoggoth.func_70097_a(Lnet/minecraft/util/DamageSource;F)Z @32: aload
  Reason:
    Type top (current frame, locals[3]) is not assignable to 'net/minecraftforge/fe/event/entity/EntityAttackedEvent' (stack map, locals[3])
  Current Frame:
    bci: @23
    flags: { }
    locals: { 'com/shinoow/abyssalcraft/common/entity/EntityLesserShoggoth', 'net/minecraft/util/DamageSource', float, top, 'net/minecraftforge/fe/event/entity/EntityAttackedEvent' }
    stack: { integer }
  Stackmap Frame:
    bci: @32
    flags: { }
    locals: { 'com/shinoow/abyssalcraft/common/entity/EntityLesserShoggoth', 'net/minecraft/util/DamageSource', float, 'net/minecraftforge/fe/event/entity/EntityAttackedEvent' }
    stack: { }
  Bytecode:
    0x0000000: bb02 3159 2ac0 0233 2b24 b702 363a 04b2
    0x0000010: 023c 1904 b602 4299 0009 1904 b402 45ac
    0x0000020: 1904 b402 4945 2bb6 024e 9900 292a 1302
    0x0000030: 502a b602 532a b401 24b6 012a 2ab4 0124
    0x0000040: b601 2a66 1301 2b6a 0c62 1302 546e b601
    0x0000050: 2f03 ac2b b202 58a6 0005 03ac 2a2b 24b7
    0x0000060: 025a ac                                
  Stackmap Table:
    append_frame(@32,Object[#561])
    same_frame(@83)
    same_frame(@92)

	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:159)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:161)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Shinoow** [comment]
That's a new one... never quite seen a crash of that type before. Did anything happen prior to the crashing? I have a theory on what could be causing it, but I need a way to test it.

**Comment by kwpugh** [comment]
Nothing that I could detect.

**Comment by Shinoow** [comment]
Closing this issue now. If it's still something that occurs, please re-open it.
On a more thorough inspection, the crash report references a bunch of events from ForgeEssentials.
